" Copyright of the Graviton Forge at the Antimatter Factory. All Rights Reserved.

" Licensed under the GNU Affero General Public License, Version 3.0.

" You may obtain a copy of the License at:
" https://www.gnu.org/licenses/agpl-3.0.en.html

set laststatus=2
set number
set wrap

